# ZSH 配置
# ~/.zshrc
# 平台：Home Manager portable core；Linux/NixOS 扩展由调用方显式接入
# 主题：Catppuccin Mocha

# ══════════════════════════════════════════════════════════════════
# 1. 🎨 终端环境与色彩
# ══════════════════════════════════════════════════════════════════
# TERM、PATH 与 session variables 由 Home Manager/base.nix 统一管理。

# 解决某些终端下 Delete/Home/End 键映射异常的问题
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# ══════════════════════════════════════════════════════════════════
# 2. 📁 环境所有权
# ══════════════════════════════════════════════════════════════════
# 不在交互启动文件中重复导出 XDG、工具链目录或 PATH。
# home/base.nix 是托管 Home Manager 会话的唯一环境来源。

# ══════════════════════════════════════════════════════════════════
# 3. 📚 历史记录
# ══════════════════════════════════════════════════════════════════
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000

setopt EXTENDED_HISTORY          # 记录命令执行的时间戳
setopt HIST_EXPIRE_DUPS_FIRST    # 当历史记录满时，优先删除重复的
setopt HIST_IGNORE_DUPS          # 忽略连续重复的命令 (ls; ls -> 只记一次)
setopt HIST_IGNORE_ALL_DUPS      # 删除历史中所有旧的重复命令
setopt HIST_IGNORE_SPACE         # 忽略以空格开头的命令 (防止密码记录)
setopt HIST_FIND_NO_DUPS         # 搜索历史时不显示重复项
setopt HIST_REDUCE_BLANKS        # 删除命令中的多余空白
setopt HIST_VERIFY               # 执行历史命令前先显示出来确认
setopt SHARE_HISTORY             # 跨终端共享历史并在命令后写入
unsetopt INC_APPEND_HISTORY      # 使用 SHARE_HISTORY 的单一历史写入模式
unsetopt NO_APPEND_HISTORY        # 清除 Home Manager 生成的冲突模式

# ══════════════════════════════════════════════════════════════════
# 4. ⚙️ Zsh 选项
# ══════════════════════════════════════════════════════════════════
setopt AUTO_CD                   # 输入目录名直接进入 (无需 cd)
setopt AUTO_PUSHD                # cd 时自动推入目录栈 (方便 popd 回去)
setopt PUSHD_IGNORE_DUPS         # 目录栈忽略重复
setopt PUSHD_SILENT              # 推入栈时不打印信息
setopt CORRECT                   # 简单的命令拼写纠错
setopt INTERACTIVE_COMMENTS      # 允许在交互式命令行输入注释 (# 后面的内容)
setopt NO_BEEP                   # 关闭烦人的蜂鸣声
setopt EXTENDED_GLOB             # 启用扩展通配符 (如 ^git 排除文件)
setopt COMPLETE_IN_WORD          # 在单词中间补全
setopt AUTO_MENU                 # 多结果时自动进入菜单
setopt NO_FLOW_CONTROL           # 禁用 Ctrl-S/Ctrl-Q 卡住终端

# Shell integrations and shared aliases are generated by Home Manager.
# Keep this file for Zsh-only functions and environment setup.

# ══════════════════════════════════════════════════════════════════
# 7. 🔨 实用函数
# ══════════════════════════════════════════════════════════════════

# 创建目录并立即进入
mkcd() {
    mkdir -p "$@" && cd "$@"
}

# 万能解压函数 (自动识别格式)
extract() {
    if [ "$#" -lt 1 ]; then
        echo "用法: extract <archive>"
        return 1
    fi

    local archive="$1"
    if [ -f "$archive" ]; then
        if command -v ouch &> /dev/null; then
            ouch decompress "$archive"
            return $?
        fi

        case "$archive" in
            *.tar.bz2)   tar xjf "$archive"    ;;
            *.tar.gz)    tar xzf "$archive"    ;;
            *.tar.xz)    tar xJf "$archive"    ;;
            *.bz2)       bunzip2 "$archive"    ;;
            *.gz)        gunzip "$archive"     ;;
            *.tar)       tar xf "$archive"     ;;
            *.tbz2)      tar xjf "$archive"    ;;
            *.tgz)       tar xzf "$archive"    ;;
            *.zip)       unzip "$archive"      ;;
            *.Z)         uncompress "$archive" ;;
            *.7z)        7z x "$archive"       ;;
            *.rar)       unrar x "$archive"    ;;
            *)           echo "'$archive' 无法识别的压缩格式" ;;
        esac
    else
        echo "'$archive' 不是有效文件"
    fi
}

# fzf: 模糊搜索文件并用 Helix 编辑
fe() {
    local file
    local preview_cmd
    if command -v bat &> /dev/null; then
        preview_cmd='bat --color=always {}'
    else
        preview_cmd='sed -n "1,200p" {}'
    fi
    file=$(fd --type f --hidden --exclude .git | fzf --preview "${preview_cmd}")
    [ -n "$file" ] && "${EDITOR:-nvim}" "$file"
}

# fzf: 模糊搜索目录并进入
fcd() {
    local dir
    dir=$(fd --type d --hidden --exclude .git | fzf --preview 'eza -la --icons {}')
    [ -n "$dir" ] && cd "$dir"
}

# ══════════════════════════════════════════════════════════════════
# 8. 🔧 补全系统
# ══════════════════════════════════════════════════════════════════
# 补全菜单配置
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'  # 大小写不敏感
if [[ -n "${LS_COLORS:-}" ]]; then
    zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # 使用 ls 的颜色
fi
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{magenta}── %d ──%f'
zstyle ':completion:*:messages' format '%F{yellow}%d%f'
zstyle ':completion:*:warnings' format '%F{red}没有找到匹配项%f'

# ══════════════════════════════════════════════════════════════════
# 9. 🔌 第三方工具集成
# ══════════════════════════════════════════════════════════════════

# Fzf 配置（Catppuccin Mocha 配色）
if command -v fzf &> /dev/null; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    export FZF_DEFAULT_OPTS='
        --height 40%
        --layout=reverse
        --border=rounded
        --preview-window=right:60%
        --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
        --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
        --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
    '
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
fi

# Directory environment and prompt integrations are generated by Home Manager.

# ══════════════════════════════════════════════════════════════════
# 🎉 欢迎语
# ══════════════════════════════════════════════════════════════════
# 如果是 Emacs 环境则不显示，防止卡死
if [[ "${TERM:-}" != "dumb" ]]; then
    if command -v fastfetch &> /dev/null; then
        # fastfetch --logo small
        fastfetch
    fi
fi
